---
name: MultiPlatformTest

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Windows
        uses: microsoft/setup-msbuild@v1
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: CMake Setup
        shell: bash
        working-directory: build
        run: |
          cmake ..

      - name: Build
        shell: bash
        working-directory: build
        run: |
          cmake --build . --config Debug

      - name: Run Tests
        shell: bash
        working-directory: build
        run: |
          cmake --build . --config Debug --target run
